# This workflow checks out code, performs an Anchore container image
# vulnerability and compliance scan, and integrates the results with
# GitHub Advanced Security code scanning feature. For more information on
# the Anchore scan action usage and parameters, see
# https://github.com/anchore/scan-action. For more information on
# Anchore container image scanning in general, see
# https://docs.anchore.com.

name: Docker (clickhouse-server)

"on":
  pull_request:
    paths:
      - docker/server/Dockerfile
      - .github/workflows/anchore-analysis.yml
  push:
    branches:
      - test
  schedule:
    - cron: '0 21 * * *'

jobs:
  Anchore-Build-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          cd docker/server
          perl -pi -e 's|=\$version||g' Dockerfile
          docker build . --file Dockerfile --tag docker.pkg.github.com/${{ lowercase(github.repository) }}/clickhouse:${{ github.sha }}
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/clickhouse:${{ github.sha }}
